LaasYath/Edu-Mobile-App-Project

components/MainNavigatorScreen.js
now correctly directs straight to HomeScreen
=> fixed MainNavigatorScreen

App.js, components/AuthHelper.js, components/HomeScreen.js, components/LoginScreen.js, package-lock.json, package.json
still need to handle require loop that arose from using context, login screen is closer to final product
=> reconfigured auth process

App.js, Contexts.js, components/AuthHelper.js, components/HomeScreen.js, components/LoginScreen.js
=> refactored auth system

components/ClubsScreen.js
still needs implementation into database (find /* comments */ in getUserClubCards and getAllClubCards)
=> added skeleton for ClubsScreen

components/GalleryScreen.js
displays images in rudimental grid. still requires functioning filter
=> skeleton for GalleryScreen

components/ClubsScreen.js
UserClubCards now work, with a loading animation too! (console logs still exist, feel free to remove whenever)
=> fixed clubs screen

App.js, components/CalendarScreen.js, components/ClubsScreen.js
TODO: implementing backend to button
=> implemented frontend club card button

Contexts.js, components/LoginScreen.js
Also added QoL for LoginScreen loading
TODO: Implement createNewAccount() in LoginScreen.js
=> implemented new account creation frontend

App.js, components/CalendarScreen.js, components/ClubsScreen.js
merge new account creation frontend
=> Big turtle8 patch 0.5.3

components/AuthHelper.js, components/GalleryScreen.js, components/MainNavigatorScreen.js
=> implemented GalleryScreen frontend

components/GalleryScreen.js
implemented posted by and captions for gallery
TODO (same as last time):
implement async getClubs()
implement adding image to gallery
implement async getFilteredImages()
implement (new) async getUserClubOptions()
should probably rename this to async getAvailableFilters()
=> updated gallery frontend to final appearance

components/GalleryScreen.js
made neater, included separation between owned and not owned clubs
TODO: Implement backend for 
- fetching clubs
- fetching images
- adding images
=> updated gallery frontend

components/ChatScreen.js, components/GalleryScreen.js
TODO:
Implement async getMessageOptions()
Implement async getMessages(name)
Implement sending message in sendMessage(to, msg)
=> Implemented Chat frontend

components/HomeScreen.js, components/home_screen/AboutScreen.js, components/home_screen/ProfileScreen.js, components/home_screen/SettingsScreen.js
TODO:
Implement profile/settings/about frontend
=> Implemented HomeScreen frontend

components/home_screen/ProfileScreen.js
TODO:
Implement async getProfileData()
Make frontend prettier
=> Implemented ProfileScreen frontend

components/CalendarScreen.js, components/ClubsScreen.js
CalendarScreen.js frontend now shows new dates
ClubScreen.js frontend now accurately displays correct clubs when joining, leaving
=> [0.11.2] fixed refresh issues for calendar, club

components/GalleryScreen.js, components/LoginScreen.js, components/home_screen/AboutScreen.js, components/home_screen/ProfileScreen.js, components/home_screen/ReportBugScreen.js, components/home_screen/SettingsScreen.js
Frontend implemented for gallery, settings, login, report bug, profile, and about screens
TODO:
- Implement async changePassword() in SettingsScreen.js
- Implement async onSubmit() in ReportBugScreen.js
- Fix GalleryScreen.js wrapping? Do not see issue on my end
=> [0.12.0] frontend for gallery, home subscreens

components/CalendarScreen.js, components/HomeScreen.js, components/LoginScreen.js, components/home_screen/ReportAbsenceScreen.js
Implemented frontend for ReportAbsenceScreen.js, also updated modals for increased uniformity
TODO:
Implement async onSubmit() for ReportAbsenceScreen.js
=> [0.13.0] Implemented report absence frontend

components/CalendarScreen.js, components/LoginScreen.js
Updated modals with additional features to avoid keyboard overlap, needs additional testing
=> [0.13.1] Updated modals

components/ClubsScreen.js, components/GalleryScreen.js
Updated separation between categories to make clearer
=> [0.13.3] Updated frontend for gallery, clubs

components/ClubsScreen.js, components/GalleryScreen.js, components/HomeScreen.js, components/LoginScreen.js
Parents should now see their child's gallery and clubs.
Also made it so parents cannot join/leave clubs or add images.
TODO:
Actually check with a parent account
=> [0.13.4] Implemented parent view in gallery, clubs

components/AnnouncementsScreen.js, components/ChatScreen.js, components/home_screen/ProfileScreen.js
ChatScreen now correctly utilizes the acquired backend information, also has search bar frontend
TODO:
Implement search bar backend
=> [0.15.0] Got chat frontend working

components/home_screen/SettingsScreen.js
Simply made settings link to settings app so user can change their own privacy settings themselves.
TODO:
check if works on iOS
=> [0.15.1] Implemented simple settings

components/CalendarScreen.js, components/LoginScreen.js
Needs checking on iOS for CalendarScreen, LoginScreen
=> [0.15.2] Attempt to fix modals overlapping on iOS

components/AnnouncementsScreen.js, components/ChatScreen.js, components/GalleryScreen.js, components/HomeScreen.js, components/MainNavigatorScreen.js, components/home_screen/ReportAbsenceScreen.js, components/home_screen/ReportBugScreen.js
Chat now updates when message is sent for user, admin screen for absences (view absences)
TODO:
Admin implementation for other screens
=> [0.15.3] Updating chat, admin absences

components/ChatScreen.js
Fixed chat bug where going to chat with different person wouldn't update the navigation appbar
=> [0.15.4] Fixed chat bug

components/ChatScreen.js, components/GalleryScreen.js, components/HomeScreen.js, components/home_screen/ReportAbsenceScreen.js
Now correctly shows View Absences vs. Report Absence
Also one image per row in gallery
=> [0.15.5] Update admin absence screen, gallery

components/ChatScreen.js
Added activity indicator while loading messages.
=> [0.15.7] Added chat activity indicator

components/LoginScreen.js
Fixed bug for creating new account
=> [0.15.8] Fix login screen

components/ChatScreen.js
Removed activity indicator (no messages appeared to be as if still loading)
=> [0.15.9] Fix chat screen

components/CalendarScreen.js
Feel free to ignore, is an incredibly minor semantic change to CalendarScreen.js
=> [0.15.11] Semantic change (can ignore)
